'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from 'next-auth/react';
import Provider from './Provider';
import { useEffect, useState } from "react";
import {LocationContext} from '../contexts/userLocationContext';
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>){
  const [location, setLocation] = useState<any>([])

  const getUserLocation = () => {
    navigator.geolocation.getCurrentPosition(function(position){
      console.log('pos', position)
      setLocation({
        lat: position.coords.latitude,
        lng: position.coords.longitude
      })
    })
  }
  useEffect(()=>{
    getUserLocation()
},[])
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
      <ToastContainer />
        <LocationContext.Provider value={{location, setLocation}}>
        <Navbar />
        {children}
        </LocationContext.Provider>
        </Provider>
        </body>
    </html>
  );
}
